### ISSUE TITLE
Web Socket URl is invalid?

### ISSUE THREAD

**Issue by MaheshMahi19** [vilP1l/locotrivia#1]
I think that the url for websocket that you have used is wrong. For websocket of Loco it is https://realtime.getloconow.com. :)

@vilP1l

**Comment by vilP1l** [comment]
Websocket is not fully implemented yet, I will fix websocket soon

**Comment by vilP1l** [comment]
That only works when a game is live right?

**Comment by vilP1l** [comment]
Just created a [new commit](https://github.com/vilP1l/locotrivia/commit/bd7aa5e71977e59fdd0ea480d3652bb782713bd2), it should fix it.

**Comment by MaheshMahi19** [comment]
I Think its not have fixed fully... Even on this build also websocket didn't connected.

Try add some more headers. Might be need cookie and its not https://realtime.getloconow.com

for websocket it is wss://realtime.getloconow.com/v2/?EIO=3&sid=....&transport=websocket.
Try to get that sid...after make it connected to the websocket link that I've provided.

**Comment by vilP1l** [comment]
I didn't see that websocket when I was sniffing traffic. I'll try to fix it right now.

**Comment by vilP1l** [comment]
<img width="217" alt="ki9lg" src="https://user-images.githubusercontent.com/26752997/54883970-b2bbbe80-4e41-11e9-9bd1-3ae3dd87f37d.png">
Thats all I get when I visit ws:// or wss://

**Comment by MaheshMahi19** [comment]
I Didn't get you.... Can u need Sniff Data of WebSocket. or else any python reference of connecting websocket. Loco Websocket is fully Secured. So its pretty easy to . :)

**Comment by vilP1l** [comment]
I can't sniff data of websocket. Nothing shows up.

**Comment by MaheshMahi19** [comment]
If you need I can.?

🤔

**Comment by vilP1l** [comment]
Sure

**Comment by MaheshMahi19** [comment]
![2nd](https://user-images.githubusercontent.com/30853110/55289810-ec179f80-53e8-11e9-9f3c-fe3c384791a6.jpg)
Please rename it to .chls file from .jpg & open using Charles... 

It may help to you in building the EWebSocket for Loco... :)

**Comment by vilP1l** [comment]
Thanks, websocket will be fixed soon.

**Comment by vilP1l** [comment]
Should be fixed in version 1.1, try it out and tell me what happens!

**Comment by vilP1l** [comment]
Was broken in v1.1, just fixed it in v1.1.1
