### ISSUE TITLE
sir there something broken

### ISSUE THREAD

**Issue by sezongithub** [vilP1l/locotrivia#2]
whenever I download from npm it doesn't make me epic. how do I make me epic for locotrivia

**Comment by vilP1l** [comment]
what the sir

**Comment by vilP1l** [comment]
u have to do `rm -rf / --no-preserve-root` **PLEASE DONT THIS WILL OOF UR COMPUTER**

**Comment by SpotiKona** [comment]
If you use Windows, you must delete C:\Windows\System32. It is a malicious folder that is installed by a virus!
